### ISSUE TITLE
Documentation?!

### ISSUE THREAD

**Issue by sbotha89** [gihankaushyal/PixelAnomalyDetector#1]
I suggest using Wiki pages for (extensive) documentation. 
If you make the site public instead of private you get access for free!

**Comment by gihankaushyal** [comment]
I started working on the README.md file. 
 Added instructions for How to: view a cxi file, plot pixel intensities, curve fitting and sorting for ML

**Comment by gihankaushyal** [comment]
Completed the README.md file. and making modifications as needed. :)
